#!/usr/bin/env bash
# Connects to server 52.23.245.33 with key in ~/.ssh/school

ssh -i ~/.ssh/school ubuntu@54.175.37.39

ssh -i ~/.ssh/school ubuntu@52.23.245.33

ssh -i ~/.ssh/school ubuntu@54.173.187.95
